apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner-1
  labels:
    app: nfs-client-provisioner-1
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner-1
  template:
    metadata:
      labels:
        app: nfs-client-provisioner-1
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner-1
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 49.247.26.88
            - name: NFS_PATH
              value: /mnt/nfs/mysql
      volumes:
        - name: nfs-client-root
          nfs:
            server: 49.247.26.88 
            path: /mnt/nfs/mysql
