# 스테이트풀셋 멤버의 안정적인 DNS 엔트리를 위한 헤드리스 서비스.
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  clusterIP: None
  selector:
    app: mariadb
---
# 읽기용 Mariadb 인스턴스에 연결하기 위한 클라이언트 서비스.
# 쓰기용은 Primary 인 mariadb-0.mariadb 에 대신 연결해야 한다.
apiVersion: v1
kind: Service
metadata:
  name: mariadb-read
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
    readonly: "true"
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: mariadb
